name: phones_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2

  firebase_core_web: ^2.6.0

  google_maps_flutter: ^2.2.4 #---------
 
  url_launcher: ^6.0.20 #-----
  image_picker: ^0.8.4+8 #-----
  day_night_time_picker: ^1.0.5 #------
  flutter_background_service: ^2.4.6 #------



  geolocator: ^9.0.2 # get user pos (gps)

  http: any

  shared_preferences: ^2.0.15 #ios Storage location : NSUserDefaults
  shared_preferences_android: ^2.0.15
  shared_preferences_foundation: ^2.1.3 # for ios

  fluttertoast: ^8.0.8
  geocoding: ^2.0.2 # convert address to latlng

  intl_phone_number_input: ^0.7.0+2
  awesome_dialog: ^3.0.2

  line_icons: ^2.0.3

  google_fonts: ^4.0.4
  path_provider: any
  open_file: any

  animated_text_kit: any
  intl: any
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  #collection: ^1.15.0

  font_awesome_flutter: ^10.4.0 #icons
  email_validator: '^2.1.16'

  custom_map_markers: ^0.0.1
  dropdown_button2: ^1.6.3 # used for item options dropdown
  settings_ui: ^2.0.2
 
  flutter_typeahead: ^4.0.0 # for textField in appbar
  responsive_sizer: ^3.1.0
  tutorial_coach_mark: ^1.2.6
  cached_network_image: any #  with downloading image
  shimmer: ^2.0.0
  qr_code_scanner: ^1.0.1
  cupertino_icons: ^1.0.2

  country_pickers: ^2.0.0

  fancy_shimmer_image: ^2.0.2
 
  auto_size_text: ^3.0.0
  timezone: any


  numberpicker: ^2.1.2
  flutter_animated_dialog: any
  connectivity_plus: ^4.0.1
  loading_indicator: ^3.1.0
  flutter_swipe_action_cell: ^3.1.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  custom_refresh_indicator: ^3.0.0
  flutter_hooks: ^0.20.5
  animations: ^2.0.8
  anim_search_bar: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/phone-logos/
