name: phones_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.0
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  firebase_auth: ^4.6.2
  #cloud_functions: any
  #firebase_messaging: any
  firebase_storage: ^11.2.2
  #firebase_analytics: ^10.4.2
  #firebase_performance: any
  #firebase_crashlytics: ^3.3.2
  firebase_core_web: ^2.6.0

  google_sign_in: any #---------
  in_app_purchase: any #---------
  google_maps_flutter: ^2.2.4 #---------
  flutter_local_notifications: ^13.0.0 #------
  #awesome_notifications: ^0.6.18+2 #------
  #awesome_notifications: ^0.6.21 #------
  url_launcher: ^6.0.20 #-----
  image_picker: ^0.8.4+8 #-----
  day_night_time_picker: ^1.0.5 #------
  flutter_background_service: ^2.4.6 #------



  flutter_inappwebview: 5.4.4
  #awesome_notifications_fcm: any
  #badges: ^2.0.3
  geolocator: ^9.0.2 # get user pos (gps)
  #flutter_map: any
  #latlong: ^0.6.1
  #carousel_slider: ^4.1.1 # for image sliding
  http: any

  shared_preferences: ^2.0.15 #ios Storage location : NSUserDefaults
  shared_preferences_android: ^2.0.15
  shared_preferences_foundation: ^2.1.3 # for ios

  fluttertoast: ^8.0.8
  geocoding: ^2.0.2 # convert address to latlng
  #geocode: ^1.0.1
  #flutter_map_marker_cluster: ^1.0.1 # to compile all nearby markers in just one
  #syncfusion_flutter_maps: ^20.1.58 # for creating beautiful, interactive, and customizable maps
  #map_launcher: ^2.1.2
  #country_state_city_picker: ^1.2.8
  intl_phone_number_input: ^0.7.0+2
  awesome_dialog: ^3.0.2
  #animated_button: ^0.2.0
  #bottom_sheet: ^3.1.1
  #expandable_bottom_bar: ^2.0.2
  line_icons: ^2.0.3

  #file_picker: ^5.2.2
  #image: ^3.1.3
  #images_picker: ^1.2.10
  #dio: ^4.0.4
  #multi_image_picker: ^4.8.1
  google_fonts: ^4.0.4
  #charts_flutter: ^0.12.0
  #csc_picker: ^0.2.6 # country state city picker
  #rating_dialog: ^2.0.3
  path_provider: any
  open_file: any

  #uuid: 3.0.6
  animated_text_kit: any
  intl: any
  flutter_rating_bar: ^4.0.1
  get: ^4.6.6
  collection: ^1.15.0

  pinch_zoom: ^1.0.0
  font_awesome_flutter: ^10.4.0 #icons
  #ionicons: ^0.2.2 #icons
  email_validator: '^2.1.16'
  #flutter_xlider: any
  #location: ^4.4.0
  #flutter_cache_manager: ^3.3.0
  custom_map_markers: ^0.0.1
  dropdown_button2: ^1.6.3 # used for item options dropdown
  #flutter_easyloading: any
  introduction_screen: any
  #date_format: any
  youtube_player_flutter: ^8.1.0
  settings_ui: ^2.0.2
  #search
  #flutter_search_bar: ^2.1.0
  #anim_search_bar: ^2.0.2
  easy_search_bar: ^2.3.1 #filter search
  flutter_typeahead: ^4.0.0 # for textField in appbar
  #flutter_native_splash: any
  responsive_sizer: ^3.1.0
  #flutter_screenutil: any
  tutorial_coach_mark: ^1.2.6
  cached_network_image: any #  with downloading image
  #meet_network_image: any # show loading indicator without downloading image
  shimmer: ^2.0.0
  #random_avatar: any
  #selectable: ^0.2.3
  #flutter_automation: ^2.0.0
  cupertino_icons: ^1.0.2
  #vies: ^1.0.2
  #country_codes: ^2.2.0
  #country_picker: ^2.0.17
  #countries_utils: ^1.0.1
  country_pickers: ^2.0.0
  #marker_icon: any
  #flutter_svg: any
  #pay: any
  #pay_android: any
  #pay_ios: any
  #meta: any
  #simple_ripple_animation: ^0.0.3
  #custom_marker: ^1.0.0
  #custom_timer: ^0.1.2
  fancy_shimmer_image: ^2.0.2
  alarm: any
  #flutter_randomcolor: ^1.0.14
  #random_x: ^0.3.1
  auto_size_text: ^3.0.0
  timezone: any

  flutter_facebook_auth: ^6.0.3

  #background_fetch: ^1.1.3
  #device_info_plus: ^8.0.0
  numberpicker: ^2.1.2
  flutter_animated_dialog: any
  flutter_advanced_drawer: ^1.3.5
  pdf: ^3.10.4
  printing: any
  connectivity_plus: ^4.0.1
  fl_chart: ^0.63.0
  flutter_launcher_icons: ^0.13.1
  loader_overlay: any
  loading_animation_widget: any
  flutter_spinkit: any
  flutter_easyloading: ^3.0.5
  loading_indicator: ^3.1.0
  easy_date_timeline: ^1.0.5
  flutter_swipe_action_cell: ^3.1.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_staggered_animations: ^1.1.1
  custom_refresh_indicator: ^3.0.0
  flutter_hooks: ^0.20.5
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/phone-logos/
